name: SecurePulse Storage CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Lancer l'architecture Multi-Site via Docker Compose
      run: docker compose up -d

    - name: Attendre l'initialisation des conteneurs
      run: sleep 10

    - name: Initialiser le Cluster GlusterFS
      run: bash ./cluster-init.sh

    - name: Test de validation - Vérification du statut Online
      run: |
        echo "Vérification que les briques sont bien en ligne..."
        docker exec gluster-paris gluster volume status securepulse-vol
        
        STATUS=$(docker exec gluster-paris gluster volume info | grep "Status:" | awk '{print $2}')
        if [ "$STATUS" != "Started" ]; then
          echo "Erreur: Le volume GlusterFS n'est pas démarré !"
          exit 1
        fi
        echo "Succès: L'architecture GlusterFS Anti-SPOF est opérationnelle !"

    - name: Nettoyage
      if: always()
      run: docker compose down -v